version: '3.8'

services:
  db:
    image: mysql
    restart: always
    container_name: resala-db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'

  server:
    build:
      context: ./
      dockerfile: Dockerfile.server
    ports:
      - '5000:5000'
    depends_on:
      - db
    environment:
      - PORT=5000
      - NODE_ENV=development
      # JWT
      - JWT_SECRET=jwt_access_sercret
      - JWT_REFRESH=jwt_refresh_secret
      - JWT_RESET=jwt_reset_secret
      - JWT_VERIFY=jwt_verify_secret
      - SERVER_URL=http://localhost:5000
      # DATABASE
      - DATABASE_URL=mysql://root:root@localhost/resala
      # AZURE CREDENTIALS
      - AZURE_STORAGE_NAME=azure_storage_name
      - AZURE_TENANT_ID=azure_tenant_id
      - AZURE_CLIENT_ID=azure_client_id
      - AZURE_CLIENT_SECRET=azure_client_secret
      - AZURE_CDN_ENDPOINT=azure_cdn_endpoint
      # GOOGLE APP CREDENTIALS FOR GOOGLE MAILING SERVICE
      - MAIL_USER=mail_user
      - MAIL_PASS=mail_pass
      # TWILIO CREDENTIALS
      - TWILIO_ACCOUNT_SID=twilio_account_sid
      - TWILIO_AUTH_TOKEN=twillio_auth_token
      - TWILIO_PHONE_NUMBER=twilio_phone_number
      # PayMob Gateway Credentials
      - PAYMOB_INTEGRATION_ID=12345
      - PAYMOB_API_URL=https://accept.paymob.com/api
      - PAYMOB_HMAC_KEY=hmac_key
      - PAYMOB_API_TOKEN=token
