services:
  db:
    image: postgres
    restart: always
    container_name: resala-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - resala-net

  s3:
    image: minio/minio
    restart: always
    container_name: resala-s3
    environment:
      MINIO_ROOT_USER: minio_key
      MINIO_ROOT_PASSWORD: minio_secret
    volumes:
      - s3-data:/mnt/data
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - resala-net
    command: 'minio server /data --console-address :9001'

  server:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile.server
    container_name: resala-server
    image: hossam7amdy/resala-server
    depends_on:
      - db
      - s3
    volumes:
      - resala-uploads:/usr/src/app/packages/server/uploads
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - NODE_ENV=test
      - SERVER_URL=http://localhost:5000
      - FRONTEND_URL=http://localhost:3000
      - JWT_SECRET=test_secret
      - JWT_REFRESH=test_refresh
      - JWT_RESET=test_reset
      - JWT_VERIFY=test_verify
      - DATABASE_URL=postgres://postgres:postgres@localhost:54320/postgres
      - MAIL_USER=mail_user
      - MAIL_PASS=mail_pass
      - TWILIO_ACCOUNT_SID=twilio_account_sid
      - TWILIO_AUTH_TOKEN=twillio_auth_token
      - TWILIO_PHONE_NUMBER=twilio_phone_number
      - PAYMOB_INTEGRATION_ID=123456
      - PAYMOB_BASE_URL=https://accept.paymob.com
      - PAYMOB_HMAC_KEY=PAYMOB_HMAC_KEY
      - PAYMOB_API_TOKEN="PAYMOB_API_TOKEN"
      - PAYMOB_PUBLIC_KEY=egy_pk_test_abc
      - PAYMOB_SECRET_KEY=egy_sk_test_abc
      - AWS_ACCESS_KEY_ID=minio_key
      - AWS_SECRET_ACCESS_KEY=minio_secret
      - S3_REGION=s3_region
      - S3_BUCKET=resala-app
      - S3_ENDPOINT='http://localhost:9000'
      - S3_BASE_URL='http://localhost:9000/resala-app'

    networks:
      - resala-net

volumes:
  db-data:
  s3-data:
  resala-uploads:

networks:
  resala-net:
    driver: bridge
