# Use node alpine image as base
FROM node:22-alpine AS build

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY yarn.lock /app/
COPY package*.json /app/
COPY packages/server/package*.json /app/packages/server/
COPY packages/shared/package*.json /app/packages/shared/

# Install dependencies
RUN yarn --frozen-lockfile

# Copy source code
COPY packages/server/ /app/packages/server/
COPY packages/shared/ /app/packages/shared/

# Build the app
RUN yarn build:shared
RUN yarn build:server

# Remove development dependencies
RUN npm prune --omit=dev

# Use node alpine image as base
FROM node:22-alpine

# Set working directory
WORKDIR /app

# Copy built files from previous stage
COPY --from=build /app/package*.json /app/
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/packages/server /app/packages/server
COPY --from=build /app/packages/shared /app/packages/shared

# Set user to node
USER node

# Create uploads directory
RUN mkdir -p /app/packages/server/uploads

# Give permissions to uploads directory
RUN chown -R node:node /app/packages/server/uploads

# Expose port
EXPOSE 5000

# Define command to run the app
CMD ["yarn", "workspace", "@resala/server", "start"]
