# Use node alpine image as base
FROM node:20-alpine AS build

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY yarn.lock /app/
COPY package*.json /app/
COPY server/package*.json /app/server/
COPY shared/package*.json /app/shared/

# Install dependencies
RUN yarn

# Copy source code
COPY server/ /app/server/
COPY shared/ /app/shared/

# Build the app
RUN yarn build:shared
RUN yarn build:server

# Remove development dependencies
RUN npm prune --production

# Use node alpine image as base
FROM node:alpine

# Set working directory
WORKDIR /app

# Copy built files from previous stage
COPY --from=build /app/package*.json /app/
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/server /app/server
COPY --from=build /app/shared /app/shared

# Create nessessary directories
RUN mkdir /app/server/uploads

# Make sure multer can write to uploads directory
RUN chown -R node:node /app/server/uploads

# Set user to node
USER node

# Expose port
EXPOSE 5000

# Define command to run the app
CMD ["npm", "run", "start:server:prod"]
