# Set the version of docker compose to use
version: '3.9'

# The containers that compose the project
services:
  db:
    image: mysql
    restart: always
    container_name: integration-tests-db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
