openapi: 3.0.0
info:
  title: "@resala/server"
  version: 1.0.0
  description: Resala server
  license:
    name: ISC
  contact:
    name: Hossam Hamdy
paths:
  /api/v1/users/{userId}:
    get:
      operationId: GetUser
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetUserResponse"
      tags:
        - User
      security:
        - jwt_auth: []
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            format: double
            type: number
    delete:
      operationId: DeleteUser
      responses:
        "200":
          description: User deleted successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeleteUserResponse"
      tags:
        - User
      security:
        - jwt_auth: []
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            format: double
            type: number
    put:
      operationId: UpdateUser
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateUserResponse"
      tags:
        - User
      security:
        - jwt_auth: []
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            format: double
            type: number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                role:
                  type: string
                  enum:
                    - ADMIN
                    - CUSTOMER
                    - MODERATOR
                lastName:
                  type: string
                firstName:
                  type: string
                phone:
                  type: string
                isVerified:
                  type: boolean
              type: object
  /api/v1/users:
    get:
      operationId: ListUsers
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListUsersResponse"
      tags:
        - User
      security:
        - jwt_auth: []
      parameters:
        - in: query
          name: limit
          required: false
          schema:
            format: double
            type: number
        - in: query
          name: page
          required: false
          schema:
            format: double
            type: number
        - in: query
          name: query
          required: false
          schema:
            type: string
  /api/v1/addresses:
    get:
      operationId: ListUserAddress
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListAddressResponse"
      tags:
        - Address
      security:
        - jwt_auth: []
      parameters:
        - in: query
          name: userId
          required: true
          schema:
            format: double
            type: number
    post:
      operationId: CreateUserAddress
      responses:
        "201":
          description: Address created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateAddressResponse"
      tags:
        - Address
      security:
        - jwt_auth: []
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                address:
                  type: string
                floor:
                  type: number
                  format: double
                building:
                  type: string
                country:
                  type: string
                street:
                  type: string
                city:
                  type: string
                state:
                  type: string
                lastName:
                  type: string
                firstName:
                  type: string
                phone:
                  type: string
                userId:
                  type: number
                  format: double
              type: object
  /api/v1/addresses/{addressId}:
    put:
      operationId: UpdateUserAddress
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateAddressResponse"
      tags:
        - Address
      security:
        - jwt_auth: []
      parameters:
        - in: path
          name: addressId
          required: true
          schema:
            format: double
            type: number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                address:
                  type: string
                floor:
                  type: number
                  format: double
                building:
                  type: string
                country:
                  type: string
                street:
                  type: string
                city:
                  type: string
                state:
                  type: string
                lastName:
                  type: string
                firstName:
                  type: string
                phone:
                  type: string
                userId:
                  type: number
                  format: double
              type: object
    delete:
      operationId: DeleteUserAddress
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeleteAddressResponse"
      tags:
        - Address
      security:
        - jwt_auth: []
      parameters:
        - in: path
          name: addressId
          required: true
          schema:
            format: double
            type: number
components:
  examples: {}
  headers: {}
  parameters: {}
  requestBodies: {}
  responses: {}
  schemas:
    DefaultResponseBody:
      properties:
        message:
          type: string
        success:
          type: boolean
      required:
        - success
      type: object
    RoleType:
      type: string
      enum:
        - ADMIN
        - CUSTOMER
        - MODERATOR
      nullable: false
    User:
      properties:
        updatedAt:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
        lastLogin:
          type: string
          format: date-time
          nullable: true
        role:
          $ref: "#/components/schemas/RoleType"
        lastName:
          type: string
        firstName:
          type: string
        phone:
          type: string
        isVerified:
          type: boolean
        email:
          type: string
        id:
          type: number
          format: double
      required:
        - updatedAt
        - createdAt
        - lastLogin
        - role
        - lastName
        - firstName
        - phone
        - isVerified
        - email
        - id
      type: object
    GetUserResponse:
      allOf:
        - $ref: "#/components/schemas/DefaultResponseBody"
        - properties:
            data:
              $ref: "#/components/schemas/User"
          required:
            - data
          type: object
    Pagination:
      properties:
        total:
          type: number
          format: double
        limit:
          type: number
          format: double
        page:
          type: number
          format: double
      required:
        - total
        - limit
        - page
      type: object
    ListUsersResponse:
      allOf:
        - $ref: "#/components/schemas/DefaultResponseBody"
        - properties:
            data:
              properties:
                users:
                  items:
                    $ref: "#/components/schemas/User"
                  type: array
                pagination:
                  $ref: "#/components/schemas/Pagination"
              required:
                - users
                - pagination
              type: object
          required:
            - data
          type: object
    DeleteUserResponse:
      $ref: "#/components/schemas/DefaultResponseBody"
    UpdateUserResponse:
      allOf:
        - $ref: "#/components/schemas/DefaultResponseBody"
        - properties:
            data:
              $ref: "#/components/schemas/User"
          required:
            - data
          type: object
    Address:
      properties:
        updatedAt:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
        lastName:
          type: string
        firstName:
          type: string
        phone:
          type: string
        address:
          type: string
          nullable: true
        floor:
          type: number
          format: double
          nullable: true
        building:
          type: string
          nullable: true
        street:
          type: string
        city:
          type: string
        state:
          type: string
        country:
          type: string
        id:
          type: number
          format: double
      required:
        - updatedAt
        - createdAt
        - lastName
        - firstName
        - phone
        - address
        - floor
        - building
        - street
        - city
        - state
        - country
        - id
      type: object
    ListAddressResponse:
      allOf:
        - $ref: "#/components/schemas/DefaultResponseBody"
        - properties:
            data:
              items:
                $ref: "#/components/schemas/Address"
              type: array
          required:
            - data
          type: object
    GetAddressResponse:
      allOf:
        - $ref: "#/components/schemas/DefaultResponseBody"
        - properties:
            data:
              $ref: "#/components/schemas/Address"
          required:
            - data
          type: object
    CreateAddressResponse:
      $ref: "#/components/schemas/GetAddressResponse"
    UpdateAddressResponse:
      $ref: "#/components/schemas/GetAddressResponse"
    DeleteAddressResponse:
      $ref: "#/components/schemas/GetAddressResponse"
  securitySchemes:
    jwt_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
servers:
  - url: http://localhost:5000
    description: Local development
  - url: http://ec2-13-49-159-109.eu-north-1.compute.amazonaws.com
    description: Development server
