pipeline {
    agent any

    tools {
      nodejs "NodeJS21.7.1"
    }

    stages {
        stage('Build') { 
            steps {
                sh 'npm run build'
            }
        }
        stage('Test') {
            steps {
                sh 'npm test'
            }
        }
    }
}