pipeline {
    agent any

    environment {
        CI = 'true'
        NODE_ENV = 'test'
    }

    tools {
      nodejs "NodeJS22.0.0"
    }

    stages {
        stage('Prepare') {
            steps {
                echo 'Preparing...'
                sh "npm install -g yarn"
                sh "yarn install"
            }
        }
        stage('Build') { 
            steps {
                echo 'Building...'
                sh 'yarn build'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing...'
                sh 'yarn test'
            }
        }
        stage('Docker Build') {
            steps {
                echo 'Building Docker Image...'
                sh 'yarn docker:build:server'
            }
        }
    }
}