name: CI

on:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Format and lint codebase
        run: |
          yarn
          yarn lint:check
          yarn format:check
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: yarn
      - name: Test server
        run: yarn test:server
      - name: Test shared
        run: yarn test:shared
      - name: Test dashboard
        run: yarn test dashboard
      - name: Test web
        run: yarn test:web

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: yarn
      - name: Build server
        run: yarn build:server
      - name: Build shared
        run: yarn build:shared
      - name: Build dashboard
        run: yarn build:dashboard
      - name: Build web
        run: yarn build:web
