name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    env:
      SERVER_URL: http://localhost:5000
      JWT_SECRET: secret
      JWT_REFRESH: secret
      JWT_RESET: secret
      JWT_VERIFY: secret
      DATABASE_URL: mysql://root:root@localhost:3306/root
      MAIL_USER: test
      MAIL_PASS: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm ci
          npm run build
          npm run test

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: npm install and lint
        run: |
          npm ci
          npm run lint
